version: "3"
services:
 web:
  container_name: unipay
  hostname: unipay
  image: ferrisuryadi/unipay
  restart: unless-stopped
  ports:
  - "5000:5000"
   
 db:
  container_name: unipay-db
  hostname: unipay-db
  image: mysql:5.7.29
  restart: unless-stopped
  ports:
  - 3300:3306
  volumes:
  - "/root/unipay/sqldata:/var/lib/mysql"
  environment:
   MYSQL_ROOT_PASSWORD: M4utauaja
   MYSQL_DATABASE: unipay
   MYSQL_USER: root
   MYSQL_PASSWORD: M4utauaja

networks:
  default:
    external:
      name: webproxy
