version: "3"
services:
 web:
  hostname: unipay
  image: ferrisuryadi/unipay
  restart: unless-stopped
  ports:
  - "5000:5000"
  environment:
   VIRTUAL_HOST: uni-pay.co, www.uni-pay.co
   LETSENCRYPT_HOST: uni-pay.co, www.uni-pay.co
   LETSENCRYPT_EMAIL: ferri.suryadi@uni-pay.co
   
 db:
  hostname: unipay-db
  image: mysql:5.7.29
  restart: unless-stopped
  ports:
  - 3300:3306
  volumes:
  - "./:/var/lib/mysql"
  environment:
   MYSQL_ROOT_PASSWORD: M4utauaja
   MYSQL_DATABASE: unipay
   MYSQL_USER: root
   MYSQL_PASSWORD: M4utauaja

 rabbit1:
  image: rabbitmq:3.8.2-management-alpine
  hostname: rabbit1
  environment:
   RABBITMQ_ERLANG_COOKIE: "By8ibYUENiMKJQ15hmPmdEoqi"
   RABBITMQ_NODENAME: rabbit1
   VIRTUAL_HOST: rabbit.uni-pay.co, www.rabbit.uni-pay.co
   LETSENCRYPT_HOST: rabbit.uni-pay.co, www.rabbit.uni-pay.co
   LETSENCRYPT_EMAIL: ferri.suryadi@uni-pay.co
  volumes:
  - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
  - "./definitions.json:/etc/rabbitmq/definitions.json"
  ports:
  - "4369:4369"
  - "5671:5671"
  - "5672:5672"
  - "15671:15671"
  - "15672:15672"
  - "25672:25672"

 rabbit2:
  image: rabbitmq:3.8.2-management-alpine
  hostname: rabbit2
  depends_on:
  - rabbit1
  environment:
   RABBITMQ_ERLANG_COOKIE: "By8ibYUENiMKJQ15hmPmdEoqi"
   RABBITMQ_NODENAME: rabbit2
  volumes:
  - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
  - "./definitions.json:/etc/rabbitmq/definitions.json"

 rabbit3:
  image: rabbitmq:3.8.2-management-alpine
  hostname: rabbit3
  depends_on:
  - rabbit1
  environment:
   RABBITMQ_ERLANG_COOKIE: "By8ibYUENiMKJQ15hmPmdEoqi"
   RABBITMQ_NODENAME: rabbit3
  volumes:
  - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
  - "./definitions.json:/etc/rabbitmq/definitions.json"

networks:
 default:
  external:
   name: webproxy