version: "3"
services:
  rabbit1:
    container_name: unipay-rabbit1
    image: rabbitmq:3-management
    hostname: rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "By8ibYUENiMKJQ15hmPmdEoqi"
      RABBITMQ_NODENAME: rabbit1
    volumes:
      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - "15672:15672"
      - "5672:5672"

  rabbit2:
    container_name: unipay-rabbit2
    image: rabbitmq:3-management
    hostname: rabbit2
    depends_on:
      - rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "By8ibYUENiMKJQ15hmPmdEoqi"
      RABBITMQ_NODENAME: rabbit2
    volumes:
      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
    
  rabbit3:
    container_name: unipay-rabbit3
    image: rabbitmq:3-management
    hostname: rabbit3
    depends_on:
      - rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "By8ibYUENiMKJQ15hmPmdEoqi"
      RABBITMQ_NODENAME: rabbit3
    volumes:
      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"

networks:
  default:
    external:
      name: webproxy
